version: "3"

services:
  core:
    image: somhunter-core
    command: sh run.sh
    ports:
      - "8082:8082"
    volumes:
      - ./somhunter-core:/somhunter-core
    networks:
      - test
      
  ui:
    image: somhunter-ui
    command: sh run.sh
    ports:
      - "8080:8080"
    volumes:
      - .:/somhunter
    networks:
      - test
  
  data-server:
    image: somhunter-data-server
    command: sh run.sh
    ports:
      - "8081:8081"
    volumes:
      - .:/somhunter
    networks:
      - test

  ranking-server:
    image: ranking-server
    command: sh run.sh
    ports:
      - "8083:8083"
    volumes:
      - ./ranking-server:/ranking-server
    networks:
      - test

networks:
  test: 
    driver: bridge
