import React from "react";
import { connect } from "react-redux";
import { Container, Row, Col, Button } from "react-bootstrap";

// ---

// *** Config generated by the Core API ***
import config from "../../../__config_generated__.json";
// *** Config generated by the Core API ***

import { useSettings } from "../../../hooks/useSettings";
import { createFetchAndSwitchSearchState } from "../../../actions/userCreator";
import Frame from "../MainWindow/Frame";

function frameCloseBtnClickHandler(s, props, e) {}

function getLikedFrames(s, props) {
  const data = props.search.likedFrames;

  const jsx = data.map((x, i) => {
    const scrFilepath = x.src;

    return (
      <li className={`liked-item`} key={`liked${i}`}>
        <Frame frame={x} />
      </li>
    );
  });

  return <>{jsx}</>;
}

function LikedPanel(props) {
  const s = useSettings();

  console.debug("<LikedPanel>: Rendering...");
  return (
    <Container fluid className="frame-list-panel liked-panel panel">
      <h5 className="small-title">Likes:</h5>
      <ul className="col-12 liked-list">{getLikedFrames(s, props)}</ul>
    </Container>
  );
}

const stateToProps = ({ user }) => {
  return { history: user.history, search: user.search };
};

export default connect(stateToProps)(LikedPanel);
