import React, { useEffect } from "react";
import { connect, useDispatch } from "react-redux";

// *** Config generated by the Core API ***
import config, { strings } from "../../__config_generated__.json";
// *** Config generated by the Core API ***

import coreApi from "../../apis/coreApi";
import * as CS from "../../constants";

import { createSetCoreSettings } from "../../actions/settingsCreator";

import { SettingsProvider } from "../../contexts/settingsContext";

import CriticalErrorWindow from "./CriticalErrorWindow";
import LoadingWindow from "./LoadingWindow";
import SomhunterUi from "./SomhunterUi";

/** JSX informing the user about critical error. */
function getErrorWindowJsx() {
  const apiCfg = config.api;
  return (
    <CriticalErrorWindow
      title={strings.ui.UNABLE_TO_FETCH_CORE_SETTINGS_HEADING}
      body={`${strings.ui.UNABLE_TO_FETCH_CORE_SETTINGS_DESC} '${apiCfg.url}${apiCfg.endpoints.settings.get.url}'`}
      action={strings.ui.UNABLE_TO_FETCH_CORE_SETTINGS_ACTION}
      actionHandler={() => window.location.reload()}
    />
  );
}

/** JSX informing the user about ongoing initial load. */
function getLoadingJsx() {
  return (
    <LoadingWindow
      title={strings.ui.LOADING_CORE_SETTINGS_HEADING}
      body={strings.ui.LOADING_CORE_SETTINGS_DESC}
    />
  );
}

/** Fetches the settings from the Core API. */
async function fetchSettings(dispatch, succ = (_) => null, fail = () => null) {
  const url = config.api.endpoints.settings.get.url;
  let response = null;

  try {
    // << Core API >>
    response = await coreApi.get(url);
    // << Core API >>
  } catch (e) {
    // Set failed state
    dispatch(createSetCoreSettings(null));

    // Run fail callback
    fail();

    return;
  }

  dispatch(createSetCoreSettings(response.data));

  // Run success callback
  succ(response.data);

  return response.data;
}

/** Initialization of the program. */
function initialize(dispatch) {
  // Successfull callback
  const succ = (coreSettings) => null;

  // Fail callback
  const fail = () => null;

  document.title = `${config.server.appName} | ${config.server.appSubname}`;

  // Fetch the back-end settings
  fetchSettings(dispatch, succ, fail);
}

function ContextWrapper({ settings }) {
  const dispatch = useDispatch();

  // Initialize the program
  useEffect(() => initialize(dispatch), []);

  // If initialize FAILED
  if (settings.coreSettings === null) {
    console.debug("<ContextWrapper>: Rendering... (ERROR LOADING)");
    return getErrorWindowJsx();
  }
  // If still LOADING
  else if (typeof settings.coreSettings === "undefined") {
    console.debug("<ContextWrapper>: Rendering... (LOADING)");
    return getLoadingJsx();
  }
  // Already LOADED
  else {
    console.debug("<ContextWrapper>: Rendering... (LOADED)");
    return (
      <SettingsProvider value={{ ...settings, dispatch }}>
        <SomhunterUi />
      </SettingsProvider>
    );
  }
}

const stateToProps = ({ settings }) => {
  return { settings };
};

export default connect(stateToProps)(ContextWrapper);
