import React, { useEffect } from "react";
import { connect, useDispatch } from "react-redux";

import { Alert, Container, Row, Col, Button } from "react-bootstrap";

// *** Config generated by the Core API ***
import config, { strings } from "../../__config_generated__.json";
// *** Config generated by the Core API ***

import coreApi from "../../apis/coreApi";
import * as CS from "../../constants";
import { hideAllSubQueries } from "../../utils/utils";

import { useSettings } from "../../hooks/useSettings";

import { crShowDisplay } from "../../actions/mainWindowCreator";
import { crNotif, crHideNotif } from "../../actions/notificationCreator";
import { createRescore } from "../../actions/rescoreCreator";
import { createSetCoreSettings } from "../../actions/settingsCreator";
import { createSetSearchState } from "../../actions/searchCreator";

import CriticalErrorWindow from "./CriticalErrorWindow";
import LoadingWindow from "./LoadingWindow";
import MainPanel from "./MainPanel/MainPanel";
import MainWindow from "./MainWindow/MainWindow";
import GlobalNotificationOverlay from "./GlobalNotificationOverlay";

/** JSX informing the user about critical error. */
function getErrorWindowJsx() {
  return (
    <CriticalErrorWindow
      title={strings.ui.UNABLE_TO_FETCH_SEARCH_STATE_HEADING}
      body={`${strings.ui.UNABLE_TO_FETCH_SEARCH_STATE_DESC} '${config.backendUrl}${config.coreSearchUrl}'`}
      action={strings.ui.UNABLE_TO_FETCH_SEARCH_STATE_ACTION}
      actionHandler={() => window.location.reload()}
    />
  );
}

/** JSX informing the user about ongoing initial load. */
function getLoadingJsx() {
  return (
    <LoadingWindow
      title={strings.ui.LOADING_SEARCH_STATE_HEADING}
      body={strings.ui.LOADING_SEARCH_STATE_DESC}
    />
  );
}

function handleGlobalKeyDown(settings, props, e) {
  const activeElement = document.activeElement;

  switch (e.keyCode) {
    case CS.KEY_CODE_TAB:
      //\todo Focus inputs....
      e.preventDefault();
      e.stopPropagation();
      break;

    case CS.KEY_CODE_ENTER:
      // If NOT in a text input
      if (activeElement.tagName !== "INPUT") {
        if (e.shiftKey) {
          props.createRescore(
            settings,
            config.ui.frameGrid.defaultSecondaryRescoreDisplay
          );
        } else {
          props.createRescore(
            settings,
            config.ui.frameGrid.defaultRescoreDisplay
          );
        }
      }
      break;

    case CS.KEY_CODE_T:
      // If NOT in a text input
      if (activeElement.tagName !== "INPUT") {
        if (e.shiftKey) {
          props.crShowDisplay(settings, CS.DISP_TYPE_TOP_N_CONTEXT);
        } else {
          props.crShowDisplay(settings, CS.DISP_TYPE_TOP_N);
        }
      }
      break;

    case CS.KEY_CODE_S:
      // If NOT in a text input
      if (activeElement.tagName !== "INPUT") {
        props.crShowDisplay(settings, CS.DISP_TYPE_SOM);
      }
      break;

    case CS.KEY_CODE_ESC:
      // Loose any focus
      document.activeElement.blur();

      // Close autocomplete
      hideAllSubQueries();

      break;

    default:
      break;
  }
}

function setupGlobalListeners(settings, props) {
  document.addEventListener("keydown", (e) =>
    handleGlobalKeyDown(settings, props, e)
  );
}

/** Fetches the search state from the Core API. */

/** Initialization of the program. */
function initializeUi(s, props) {
  // Successfull callback
  const succ = () => {
    setupGlobalListeners(s, props);
    props.crShowDisplay(s, CS.DISP_TYPE_TOP_N, 0, 0);
  };

  // Fail callback
  const fail = () => null;

  s.dispatch(createSetSearchState(s, succ, fail));
}

function SomhunterUi(props) {
  const settings = useSettings();
  const searchState = props.search;

  // Initial setup
  useEffect(() => initializeUi(settings, props), []);

  // If initialize FAILED
  if (searchState === null) {
    console.debug("<SomhunterUi>: Rendering... (ERROR LOADING SEARCH STATE)");
    return getErrorWindowJsx();
  }
  // If still LOADING
  else if (_.isEmpty(searchState)) {
    console.debug("<SomhunterUi>: Rendering... (LOADING)");
    return getLoadingJsx();
  }
  // Already LOADED
  else {
    console.debug("<SomhunterUi>: Rendering... (LOADED SEARCH STATE)");
    return (
      <Container fluid className="section somhunter-ui p-0">
        <GlobalNotificationOverlay />

        {/* <DebugButtons /> */}

        <Row noGutters>
          <Col xs={3}>
            <MainPanel />
          </Col>
          <Col xs={9}>
            <MainWindow />
          </Col>
        </Row>
      </Container>
    );
  }
}

const stateToProps = ({ search }) => {
  return { search };
};

const actionCreators = {
  crNotif,
  crHideNotif,
  crShowDisplay,
  createRescore,
  createSetCoreSettings,
};

export default connect(stateToProps, actionCreators)(SomhunterUi);
