import React from "react";

import { Modal, Button, Container } from "react-bootstrap";

// *** Config generated by the Core API ***
import config from "../../../__config_generated__.json";
// *** Config generated by the Core API ***

function ZoomWindow(props) {
  return (
    <Modal
      {...props}
      backdrop={false}
      enforceFocus={false}
      keyboard={false}
      autoFocus={false}
      animation={false}
      size="sm"
      aria-labelledby="contained-modal-title-vcenter"
      centered
      className="zoom-window off-canvas-window window"
    >
      <Modal.Body>
        <img
          src={`${config.ui.media.framesPathPrefix}${props.src}`}
          alt={props.id}
        />
      </Modal.Body>
    </Modal>
  );
}

export default ZoomWindow;
