// *** Config generated by the Core API ***
import config from "../__config_generated__.json";
// *** Config generated by the Core API ***

import * as CS from "../constants";
import { get } from "../apis/coreApi";

export function createHideDetailWindow() {
  return {
    type: CS.HIDE_DETAIL_WINDOW,
    payload: null,
  };
}

export function createShowDetailWindow(settings, frameId) {
  return async (dispatch, _) => {
    // GET params
    const params = {
      frameId: frameId,
      logIt: true,
    };

    const requestSettings = config.api.endpoints.frameDetail;
    // << Core API >>
    const response = await get(dispatch, requestSettings.get.url, { params });
    // << Core API >>

    if (response === null) return;

    // If empty array returned
    if (response.data.frames.length === 0) return;

    dispatch({
      type: CS.SHOW_DETAIL_WINDOW,
      payload: {
        pivotFrameId: frameId,
        videoId: null, // \todo Not send from the core
        frames: response.data.frames,
      },
    });
  };
}
