// *** Config generated by the Core API ***
import config from "../__config_generated__.json";
// *** Config generated by the Core API ***

import { get } from "../apis/coreApi";
import * as CS from "../constants";

export function createHideReplayWindow() {
  return {
    type: CS.HIDE_REPLAY_WINDOW,
    payload: null,
  };
}

export function createScrollReplayWindow(settings, deltaX) {
  return {
    type: CS.SCROLL_REPLAY_WINDOW,
    payload: {
      deltaX: deltaX,
    },
  };
}

export function createShowReplayWindow(settings, frameId, curPos) {
  return async (dispatch, _) => {
    // GET params
    const params = {
      frameId: frameId,
      logIt: false, // This is just exploitation of the detail fetch, don't log it!
    };

    const requestSettings = config.api.endpoints.frameDetail;
    // << Core API >>
    const response = await get(dispatch, requestSettings.get.url, { params });
    // << Core API >>

    // If empty array returned
    if (response.data.frames.length === 0) return;

    dispatch({
      type: CS.SHOW_REPLAY_WINDOW,
      payload: {
        pivotFrameId: frameId,
        frames: response.data.frames,
        cursorPos: curPos,
      },
    });
  };
}
