// *** Config generated by the Core API ***
import config from "../__config_generated__.json";
// *** Config generated by the Core API ***

import * as CS from "../constants";
import { get } from "../apis/coreApi";

export function createSetSearchState(s, succ = () => null, fail = () => null) {
  return async (dispatch, _) => {
    const url = config.api.endpoints.searchContext.get.url;

    // << Core API >>
    const res = await get(dispatch, url);
    // << Core API >>

    // If failed
    if (res === null) {
      fail();
      dispatch({
        type: CS.SET_SEARCH_STATE,
        payload: null,
      });
    }

    succ();
    dispatch({
      type: CS.SET_SEARCH_STATE,
      payload: { ...res.data },
    });
  };
}
