// *** Config generated by the Core API ***
import config from "../__config_generated__.json";
// *** Config generated by the Core API ***

import * as CS from "../constants";
import { get } from "../apis/coreApi";

export function createSetUserHistory(
  s,
  history,
  currCtxId = null,
  succ = () => null,
  fail = () => null
) {
  return {
    type: CS.SET_USER_HISTORY,
    payload: { history, currCtxId },
  };
}

export function createFetchAndSetUserState(
  s,
  succ = () => null,
  fail = () => null
) {
  return async (dispatch, _) => {
    const url = config.api.endpoints.userContext.get.url;

    // << Core API >>
    const res = await get(dispatch, url);
    // << Core API >>

    // If failed
    if (res === null) {
      fail();
      dispatch(createSetUserState(null));
    } else {
      succ();
      dispatch(createSetUserState(res.data));
    }
  };
}

export function createSetUserState(pl) {
  return {
    type: CS.SET_USER_STATE,
    payload: pl,
  };
}
