// *** Config generated by the Core API ***
import config from "../__config_generated__.json";
// *** Config generated by the Core API ***

import * as CS from "../constants";
import { get, post } from "../apis/coreApi";
import {
  crErrNotif,
  crInfoNotif,
  crHideNotif,
} from "../actions/notificationCreator";
import { crShowDisplay } from "../actions/mainWindowCreator";
import { takeScreenshotOfElem } from "../utils/utils";

export function createSetUserHistory(
  s,
  history,
  currCtxId = null,
  succ = () => null,
  fail = () => null
) {
  return async (dispatch, getState) => {
    const state = getState();

    // Recostruct the search context
    const search = { ...state.user.search };
    search.screenshotFilepath = "";
    search.id = currCtxId;

    dispatch({
      type: CS.SET_USER_HISTORY,
      payload: { ...state.user, history, search },
    });
  };
}

export function createAddLiked(s, likedFrame) {
  return {
    type: CS.ADD_LIKED_FRAME,
    payload: likedFrame,
  };
}

export function createFetchAndAddBookmarked(s, frame) {
  return async (dispatch, _) => {
    const url = config.api.endpoints.searchBookmark.post.url;
    console.info(frame);
    const reqData = {
      frameId: frame.id,
    };

    const res = await post(dispatch, url, reqData);
    if (res === null) return;

    if (res.data.isBookmarked) {
      dispatch({
        type: CS.ADD_BOOKMARKED_FRAME,
        payload: frame,
      });
    } else {
      dispatch(createRemoveBookmarked(s, frame.id));
    }
  };
}

export function createAddBookmarked(s, bookmarkedFrame) {
  return {
    type: CS.ADD_BOOKMARKED_FRAME,
    payload: bookmarkedFrame,
  };
}

export function createRemoveLiked(s, id) {
  return {
    type: CS.REMOVE_LIKED_FRAME,
    payload: id,
  };
}

export function createResetLiked(s) {
  return {
    type: CS.RESET_LIKED_FRAMES,
    payload: null,
  };
}

export function createRemoveBookmarked(s, id) {
  return {
    type: CS.REMOVE_BOOKMARKED_FRAME,
    payload: id,
  };
}

export function createResetBookmarked(s) {
  return {
    type: CS.RESET_BOOKMARKED_FRAMES,
    payload: null,
  };
}

export function createFetchAndSetUserState(
  s,
  succ = () => null,
  fail = () => null
) {
  return async (dispatch, _) => {
    const url = config.api.endpoints.userContext.get.url;

    // << Core API >>
    const res = await get(dispatch, url);
    // << Core API >>

    // If failed
    if (res === null) {
      fail();
      dispatch(createSetUserState(null));
    } else {
      succ();
      dispatch(createSetUserState(res.data));
    }
  };
}

export function createSetUserState(pl) {
  return {
    type: CS.SET_USER_STATE,
    payload: pl,
  };
}

export function createFetchAndSwitchSearchState(
  s,
  ctxId,
  succ = () => null,
  fail = () => null
) {
  return async (dispatch, getState) => {
    const state = getState();
    dispatch(crInfoNotif(s, "Working..."));

    const srcSearchCtxId = state.user.search.id;
    const url = config.api.endpoints.searchContext.post.url;

    // Take a screenshot
    let screenData = "";
    // Does this screen still lack the screenshot

    if (state.user.search.screenshotFilepath === "") {
      const frs = state.mainWindow.frames;

      screenData = await takeScreenshotOfElem(
        document.getElementById("mainGrid"),
        frs
      );
    }

    const reqData = {
      srcSearchCtxId: srcSearchCtxId,
      screenshotData: screenData,
      id: ctxId,
    };

    // << Core API >>
    const res = await post(dispatch, url, reqData);
    // << Core API >>

    // If failed
    if (res === null) {
      fail();
      return;
    }
    const displayType = res.data.search.displayType;
    succ();
    dispatch(createSetUserState(res.data));

    // Switch to the according display
    dispatch(crShowDisplay(s, config.ui.frameGrid.defaultRescoreDisplay));

    dispatch(crHideNotif(s));
  };
}
