// *** Config generated by the Core API ***
import config from "../__config_generated__.json";
// *** Config generated by the Core API ***

import * as CS from "../constants";

export function createShowZoomWindow(s, frame) {
  //console.log("creator: SHOW_REPLAY_WINDOW", frame.id, frame.src);

  return {
    type: CS.SHOW_ZOOM_WINDOW,
    payload: {
      pivotFrameId: frame.id,
      src: frame.src,
      show: true,
    },
  };
}

export function createHideZoomWindow() {
  //console.log("creator: HIDE_ZOOM_WINDOW");

  return {
    type: CS.HIDE_ZOOM_WINDOW,
    payload: null,
  };
}
