import axios from "axios";

// *** Config generated by the Core API ***
import config from "../__config_generated__.json";
// *** Config generated by the Core API ***

import { isErrDef } from "../utils/utils";
import { crReqFailNotif } from "../actions/notificationCreator";

const coreApi = axios.create({
  baseURL: config.api.url,
  withCredentials: true,
});

export async function post(dispatch, url, data = {}, cfg = {}) {
  let res = null;
  try {
    res = await coreApi.post(url, data, cfg);
  } catch (e) {
    const msg = isErrDef(e) ? e.response.data.error.message : e.message;
    dispatch(crReqFailNotif({}, url, msg));
  }

  return res;
}

export async function get(dispatch, url, cfg = {}) {
  let res = null;

  try {
    res = await coreApi.get(url, cfg);
  } catch (e) {
    const msg = isErrDef(e) ? e.response.data.error.message : e.message;
    dispatch(crReqFailNotif({}, url, msg));
  }

  return res;
}

export default coreApi;
